### ISSUE TITLE
docker-compose failed to start.

### ISSUE THREAD

**Issue by 99Kies** [subquery/subql-starter#60]
my start command:
```shell
$ docker-compose pull & docker-compose up
```

this is subquery node log:
```
 /usr/local/lib/node_modules/@subql/node/dist/main.js

- /usr/local/lib/node_modules/@subql/node/bin/run

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)

    at Function.Module._load (node:internal/modules/cjs/loader:804:27)

    at Module.require (node:internal/modules/cjs/loader:1028:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at Object.<anonymous> (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js:23:19)

    at Module._compile (node:internal/modules/cjs/loader:1126:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)

    at Module.load (node:internal/modules/cjs/loader:1004:32)

    at Function.Module._load (node:internal/modules/cjs/loader:839:12)

    at Module.require (node:internal/modules/cjs/loader:1028:19) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js',

    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/index.js',

    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/meta/mmrQuery.controller.js',

    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/meta/index.js',

    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/index.js',

    '/usr/local/lib/node_modules/@subql/node/dist/main.js',

    '/usr/local/lib/node_modules/@subql/node/bin/run'

  ]

}
```

**Comment by 99Kies** [comment]
```shell
$ docker run -it --name test-subquery-node onfinality/subql-node

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '@subql/node-core/indexer'
Require stack:
- /usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js
- /usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/index.js
- /usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/meta/mmrQuery.controller.js
- /usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/meta/index.js
- /usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/index.js
- /usr/local/lib/node_modules/@subql/node/dist/main.js
- /usr/local/lib/node_modules/@subql/node/bin/run
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js:23:19)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js',
    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/index.js',
    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/meta/mmrQuery.controller.js',
    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/meta/index.js',
    '/usr/local/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/index.js',
    '/usr/local/lib/node_modules/@subql/node/dist/main.js',
    '/usr/local/lib/node_modules/@subql/node/bin/run'
  ]
}
```

**Comment by bz888** [comment]
have you ran `yarn` && `yarn codegen` && `yarn build` prior starting it with docker ?
